### PR TITLE
The completed notebook of the tutorial.

### PR DESCRIPTION
**Pull request by emunaibari**
The complete task of the tutorial.

### CODE REVIEW

**Comment by eschalkargans** [comment]
Hi, 
Thanks for your PR (Pull Request)
I will have a look at it this afternoon!

**Comment by emunaibari** [comment]
> Hi, Thanks for your PR (Pull Request) I will have a look at it this afternoon!

Hi Etienne,
Sounds good, I hope the request done correctly as it's my first in GitHub :)

**Comment by emunaibari** [comment]
> > Hi, Thanks for your PR (Pull Request) I will have a look at it this afternoon!
> 
> Hi Etienne, Sounds good, I hope the request done correctly as it's my first in GitHub :)

I guess I forgot to put my ID (emunaibari/) in the branch name. I know it's not a big deal at this time, but I guess it's a good practice when working with GitHub, right?

**Comment by eschalkargans** [comment]
> Sounds good, I hope the request done correctly as it's my first in GitHub :)

Yes, it's done properly: the PR is requesting to merge your branch (`tutorial-solution`) into the `main` branch.  ✔️ 

> I guess I forgot to put my ID (emunaibari/) in the branch name. I know it's not a big deal at this time, but I guess it's a good practice when working with GitHub, right?

Yes it is not a big deal for this tutorial project. The branch naming convention specific is team specific, but as a "universal globally accepted rule" I usually start by my name, and precise `feature`, `bugfix`, `chore` etc eg `feature/eschalk/add-some-stuff` or `bugfix/eschalk/fix-some-bug`, or `chore/eschalk/clean-something`



-----

Note: GitHub supports markdown so you can use it in your issue descriptiosn, eg put text in **bold**, _italic_, 

## titles,

refer issues and pull requests #22  (here it refers to itself), `inline code`, 

```python
def some_code_that_is_syntaxically_colored():
   return 1234
```

- unordered 
- list

1. number
2. lists

- [ ] TODO 
- [x] Lists

horizontal bars 

-----

and other GitHub features like tagging @emunaibari , emojis :fire:

**Review by eschalkargans — APPROVED** [review]

**Pull request merged**
